# Generated by Django 4.2 on 2024-05-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactivos',
            name='fecha_de_carga',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
